### ISSUE TITLE
Keyboard visibility is not updated when changing screens on (some) Android devices

### ISSUE THREAD

**Issue by julescmay** [MisterJimson/flutter_keyboard_visibility#53] opened 2020-12-10 18:51 UTC
In my app, I have a screen A (which doesn't use keyboard visibility), but does have several controls, including text editors.  This screen navigates to another screen B, which does use keyboard visibility.  What I'm finding is: if the keyboard is visible on Screen A at the point of navigation, then `isVisible `returns true on screen B even though it's not.  Furthermore, if I introduce a third screen C (which nether shows a keyboard nor uses keyboard visibility), and I navigate A (showing keyboard) -push->  C -pop-> A (now not showing keyboard) -push-> B (not showing keyboard), `isVisible `again returns true on B.

But only sometimes: I have a Galaxy Alpha (Android 5.02) which works properly every time, and I have a Huawei CLT-L09 (Android 10) which gets it wrong every time.  (I've also seen the fault on some current Samsungs).

From my very brief perusal of the code, it would seem that when an edit control is unfocussed by a screen change, the original screen never gets rebuilt, which means that `FlutterKeyboardVisibilityPlugin.onGlobalLayout()` doesn't get called - and it doesn't get called when the new screens are being built, either. 

I know this behaviour is outside your control, but I tried (and failed) to find any way to ask the module to reset its state based on the current state of the screen (rather than the tally of callbacks).   Do you think it would be possible to modify the `isVisible` getter to really go and find out what's on the screen now (and reset the internal flag) rather than just trusting that all the notifications have arrived safely?  (Or even, adding a "synchronise" function to do the same?)  In the meantime, can you think of a workaround to force an update from the push and pop calls?

Thanks

**Comment by julescmay** [comment] 2020-12-10 23:05
>  In the meantime, can you think of a workaround to force an update from the push and pop calls?

I've thought of one!  The value returned by `isVisible` is unreliable, but the value provided by `onChange` is always good.  I was using `isVisible` to initialise the widget state, but (I think) when the widget is being intiialised, there isn't going to be a keyboard showing, because nothing text-entry-like will be focussed.  So, instead of initialising my own visible state to `isVisible`, I just initialise it to false.  

This does mean that I have to use `onChange` to monitor the keyboard visibility.  `KeyboardVisibilityProvider` shows the same problem.

**Comment by MisterJimson** [comment] 2020-12-11 13:14
@julescmay thats interesting because `isVisible` is just the newest value from `onChange`, nothing else. Starts at false.

They way I would want to fix or improve this would be the last comment here: #23

**Comment by MisterJimson** [comment] 2020-12-11 13:16
Still in alpha unfortunately

**Comment by julescmay** [comment] 2020-12-11 15:43
@MisterJimson :  isVisible is just the newest value from onChange, nothing else. Starts at false.

Yes, I saw that in the code.  What I think is happening is: when screen A first appears `_isVisible `is false.  Then screen A shows a keyboard, and you get the `onChange` notification and `_isVisible `becomes true.  Then screen A navigates to screen B, hiding the keyboard as it does so, but during that process the `onChange` notification may or may not arrive (depending on the Android version, I think).  Thus when screen B is shown, `_isVisible `is still true, and screen B doesn't generate `onChange `either.  `_isVisible `(actually most of the code) is static, so it doesn't get reset between screen A and B.

If it's helpful, I can put a quick demo app together?  Might take me a few days, while I move other work out of the way.

**Comment by MisterJimson** [comment] 2020-12-11 18:18
That makes sense. No demo needed, all good. Will see what is possible.

**Comment by ajaygautam** [comment] 2020-12-23 15:44
Could this be applicable to iOS (14.3) too?

Wondering if this is related to https://github.com/MisterJimson/flutter_keyboard_visibility/issues/37

**Comment by MisterJimson** [comment] 2021-02-11 15:38
`4.0.4-beta.0` is available with a new Android implementation using the fairly new WindowInsetsCompat features.

Any feedback is appreciated before I merge this into a main version. I suspect it may help with this issue.

**Comment by MisterJimson** [comment] 2021-02-20 21:16
Should be closed in 4.0.4, but I had trouble reproducing. Feel free to reopen with more info.

**Closed by MisterJimson** 2021-02-20 21:16 UTC
Labels: bug
