### ISSUE TITLE
 uses or overrides a deprecated API

### ISSUE THREAD

**Issue by hasanm08** [MisterJimson/flutter_keyboard_visibility#91] opened 2021-09-29 08:38 UTC
**Describe the bug**
```
\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-5.0.3\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API.
```

**To Reproduce**
run
flutter build apk
version 2.5.1

**Comment by MisterJimson** [comment] 2021-09-29 12:25
Dupe of #88

**Closed by MisterJimson** 2021-09-29 12:25 UTC
Labels: bug
