### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by fikretonuresen** [MisterJimson/flutter_keyboard_visibility#95] opened 2021-10-12 12:46 UTC
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-5.0.3\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by MisterJimson** [comment] 2021-10-12 12:46
Dupe of #88

**Closed as completed by MisterJimson** 2021-10-12 12:46 UTC
Labels: bug
