### ISSUE TITLE
Says, it uses or overrides a deprecated API when building

### ISSUE THREAD

**Issue by karskit** [MisterJimson/flutter_keyboard_visibility#13] opened 2020-04-23 11:35 UTC

**Comment by MisterJimson** [comment] 2020-04-23 11:49
Can you share the specific error message?

**Comment by MisterJimson** [comment] 2020-04-23 11:50
And the platform you are building for.

**Comment by karskit** [comment] 2020-04-23 12:44
Android and IOS app

**Comment by MisterJimson** [comment] 2020-04-23 12:48
Without sharing the specific error message or more information, it's going to be difficult to look into this.

**Comment by karskit** [comment] 2020-04-23 12:51
https://imgur.com/L1w4AcW

This is the only thing I got after I added the library, will let you know if I get some more information on the error.

**Comment by MisterJimson** [comment] 2020-04-23 13:00
Thanks for that detail.

I have definitely seen that before when using Flutter plugins, bit I can't reproduce that in the example project when using `flutter_keyboard_visibility` only.

Here is a sample of the build output when building the example app on Android.
```
jrai@Jasons-MacBook-Pro example % flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      68.0s
✓ Built build/app/outputs/apk/release/app-release.apk (15.6MB).
```

Also see some more info here: https://github.com/flutter/flutter/issues/47816

May be related to your minSdk. It also seems like just a warning, so there may be nothing to change.

**Comment by MisterJimson** [comment] 2020-04-28 11:49
Going to close this as I can't reproduce and its not clear that the warning is from this library.

**Closed by MisterJimson** 2020-04-28 11:49 UTC
