### ISSUE TITLE
Deprecated API Note

### ISSUE THREAD

**Issue by codenoobforreal** [MisterJimson/flutter_keyboard_visibility#90] opened 2021-09-16 13:25 UTC
**Describe the bug**
<img width="919" alt="C664845E-EC3A-41C6-8EDC-5232BB357B8F" src="https://user-images.githubusercontent.com/18373253/133619532-a6fe21a8-f5ab-42be-9ffd-d18ac3a54ec6.png">

**To Reproduce**
flutter build apk

**Expected behavior**

**Info (please complete the following information):**
`flutter_keyboard_visibility` version: 5.0.3
Reproducible on platforms (Android, iOS, etc):
`flutter doctor` output:
 <img width="839" alt="9B8C102D-5C4B-432B-AFC8-69359EC13FD2" src="https://user-images.githubusercontent.com/18373253/133619686-66d562ae-a326-4c7b-8e90-a28023ea9a32.png">
**Additional context**

**Comment by codenoobforreal** [comment] 2021-09-16 13:27
I don't know if it is appropriate to submit this kind of issue here.If not.Just close it.

**Comment by MisterJimson** [comment] 2021-09-16 17:56
Dupe of #88

**Closed by MisterJimson** 2021-09-16 17:56 UTC
Labels: bug
